/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brightoilonline_c2b_phone_utils_JniUtil */

#ifndef _Included_com_brightoilonline_c2b_phone_utils_JniUtil
#define _Included_com_brightoilonline_c2b_phone_utils_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brightoilonline_c2b_phone_utils_JniUtil
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_brightoilonline_c2b_1phone_utils_JniUtil_getKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
